import 'server-only';
import {createHmac} from 'node:crypto';
import {NextRequest,NextResponse} from 'next/server';
import {ZodError} from 'zod';
import {adminServices} from './firebase-admin';
export class HttpError extends Error { constructor(public status:number,message:string){super(message);} }
export function hash(value:string) { return createHmac('sha256',process.env.LOOKUP_HASH_SECRET!).update(value).digest('hex'); }
export async function body(req:NextRequest) { const origin=req.headers.get('origin'); if (!process.env.APP_URL || origin !== new URL(process.env.APP_URL).origin) throw new HttpError(403,'Request origin was not accepted. Refresh this page and try again.'); const raw=await req.text(); if(raw.length>65000) throw new HttpError(413,'Request is too large.'); try { const parsed=JSON.parse(raw); if(!parsed || typeof parsed!=='object' || Array.isArray(parsed)) throw new Error(); return parsed; } catch {throw new HttpError(400,'Invalid request.');} }
export async function requireAdmin(req:NextRequest) { const token=req.headers.get('authorization')?.replace(/^Bearer /,''); if(!token) throw new HttpError(401,'Sign in to continue.'); try {const user=await adminServices().auth.verifyIdToken(token,true); if(user.admin !== true) throw new Error(); return user.uid;} catch {throw new HttpError(403,'An administrator account is required.');} }
export async function throttle(key:string,limit:number) { const {db}=adminServices(); const bucket=Math.floor(Date.now()/3600000); const ref=db.doc(`rateLimits/${hash(key+bucket)}`); await db.runTransaction(async tx=> {const snap=await tx.get(ref); const count=snap.data()?.count ?? 0; if(count>=limit) throw new HttpError(429,'Too many attempts. Please try again in an hour.'); tx.set(ref,{count:count+1,expiresAt:new Date((bucket+2)*3600000)});}); }
export function fail(error:unknown) { if(error instanceof ZodError) return NextResponse.json({error:error.issues.map(i=>`${i.path.join('.') || 'Form'}: ${i.message}`).join(' ')},{status:400}); if(error instanceof HttpError) return NextResponse.json({error:error.message},{status:error.status}); if(error instanceof Error && error.message==='SETUP_REQUIRED') return NextResponse.json({error:'Online registration is being prepared. Please contact our office for help.'},{status:503}); console.error('API request failed',error instanceof Error ? error.name : 'unknown'); return NextResponse.json({error:'We could not complete your request. Please try again.'},{status:500}); }
export const privateHeaders={'Cache-Control':'no-store'};