import {Analytics} from '@vercel/analytics/next';
import {MobileMenu} from '@/components/mobile-menu';
import {getSiteSettings} from '@/lib/settings-server';
import {phoneLabel} from '@/lib/site-settings';
import {SiteSettingsProvider} from '@/components/site-settings-provider';
export const dynamic='force-dynamic';
import {siteUrl, socialMetadata} from '@/lib/site';
import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import './globals.css';
export const metadata:Metadata={metadataBase:new URL(siteUrl),openGraph:socialMetadata('Practical AI training in Liberia','/'),twitter:{card:'summary_large_image',images:['/mcl-logo.png']},verification:{google:process.env.GOOGLE_SITE_VERIFICATION},title:{default:'Modern Communication Links | Practical AI training in Liberia',template:'%s | Modern Communication Links'},description:'Learn practical AI skills with Michael Khan and Teddy Morris in Liberia. Explore workshops, register without an account, and pay in person.'};
const nav=[['/about','About'],['/program','Program'],['/workshops','Workshops'],['/contact','Contact']];
export default async function RootLayout({children}:{children:React.ReactNode}){const settings=await getSiteSettings();return <html lang="en"><body><SiteSettingsProvider settings={settings}><a className="skip" href="#main">Skip to content</a><div className="topline"><span>Practical skills. Local connections. New possibilities.</span><Link href="/status">Check your registration ↗</Link></div><header className="site-header"><Link href="/" className="brand" aria-label="Modern Communication Links home"><Image className="brand-logo" src="/mcl-logo.png" alt="" width={90} height={60} priority/><span>Modern<br/>Communication Links</span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav><Link className="button small header-cta" href="/workshops">Find a workshop <span>↗</span></Link><MobileMenu links={[...nav,['/register','Register'],['/status','Registration status']]}/></header><main id="main">{children}</main><footer><div className="footer-grid"><div><Link href="/" className="brand footer-brand"><Image className="brand-logo" src="/mcl-logo.png" alt="" width={90} height={60}/><span>Modern<br/>Communication Links</span></Link><p>Practical AI learning.<br/>Right here in Liberia.</p></div><div><h3>Explore</h3><Link href="/program">Training program</Link><Link href="/workshops">Upcoming workshops</Link><Link href="/gallery">Gallery</Link><Link href="/testimonials">Testimonials</Link></div><div><h3>Here to help</h3><Link href="/faq">Frequently asked questions</Link><Link href="/status">Registration status</Link><Link href="/verify">Verify a certificate</Link><Link href="/contact">Contact us</Link><Link href="/feedback">Leave feedback</Link></div><div><h3>Let’s connect</h3><a href={"tel:"+settings.phone1}>{phoneLabel(settings.phone1)}</a><a href={"tel:"+settings.phone2}>{phoneLabel(settings.phone2)}</a><a href={"mailto:"+settings.email}>Email our team ↗</a><a href={settings.facebook} target="_blank" rel="noreferrer">Facebook ↗</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Modern Communication Links</span><span>Made for curious minds in Liberia.</span><Link href="/admin">Staff sign in</Link></div></footer></SiteSettingsProvider><Analytics/></body></html>}