import {notFound} from 'next/navigation';
import Link from 'next/link';
import {Heading,ProgramCards,Trainers,WorkshopList,PaymentNote} from '@/components/public';
import {publicData} from '@/lib/public-data';
import {office} from '@/lib/schema';
const names:Record<string,string>={about:'About us',program:'Training program',workshops:'Upcoming workshops',gallery:'Workshop gallery',testimonials:'Learner stories',faq:'Frequently asked questions',contact:'Let’s connect'};
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{page:string}>}){const {page}=await params;return {title:names[page]||'Page not found'};}
export default async function PublicPage({params}:{params:Promise<{page:string}>}){const {page}=await params;if(!names[page])notFound();const data=await publicData();return <><Heading eyebrow="MODERN COMMUNICATION LINKS" title={names[page]}/><section className="wrap page-content">
{page==='about'&&<><div className="editorial"><h2>Making new technology<br/>feel within reach.</h2><div><p>Modern Communication Links brings practical AI training to learners in Liberia. Our workshops are designed to help people explore useful tools and put them to work in everyday life.</p><p>We welcome students, business owners, professionals, and anyone ready to learn. Our approach is simple: understand the basics, practice together, and build confidence one step at a time.</p></div></div><h2 className="subheading">The people you’ll learn with</h2><Trainers content={data.content}/></>}
{page==='program'&&<><p className="lead intro">A practical learning path, from your first prompt to a project of your own. Each workshop’s published program contains its exact sessions and schedule.</p><ProgramCards/><div className="two-grid section"><div><h2>Come ready to try.</h2><p>Bring a notebook and, if available, a charged smartphone or laptop. Contact us before registering if you need help with device or internet arrangements.</p></div><div className="card"><h3>Responsible AI, from the start</h3><p>Practice checking information, protecting private data, and knowing when human judgement matters. AI is a useful assistant; your judgement stays essential.</p><Link className="button" href="/workshops">View workshop schedules ↗</Link></div></div></>}
{page==='workshops'&&<><p className="lead intro">Choose a session that works for you. All times are local to Liberia. Your seat is confirmed after payment at our office.</p><WorkshopList workshops={data.workshops} state={data.state}/><PaymentNote/></>}
{page==='gallery'&&(data.content.gallery.length?<div className="three-grid gallery">{data.content.gallery.map((g,i)=><figure key={i}><img src={g.url} alt={g.caption} width={640} height={480} loading="lazy"/><figcaption>{g.caption}</figcaption></figure>)}</div>:<div className="empty-state"><span className="large-symbol">↗</span><h2>Learning, in the making.</h2><p>Photos from our workshops will be shared here with participants’ permission.</p><Link className="button" href="/workshops">Explore upcoming workshops</Link></div>)}
{page==='testimonials'&&(data.content.testimonials.length?<div className="three-grid">{data.content.testimonials.map((t,i)=><figure className="card quote" key={i}><blockquote>“{t.quote}”</blockquote><figcaption><strong>{t.name}</strong><br/>{t.detail}</figcaption></figure>)}</div>:<div className="empty-state"><h2>The next story could be yours.</h2><p>We’ll share feedback here as our learners complete their workshops.</p><Link className="button" href="/workshops">Find a workshop</Link></div>)}
{page==='faq'&&<div className="faq-list">{[['Do I need experience with AI?','No. Our introductory workshops are designed for beginners. Check each workshop’s program for any specific requirements.'],['How much does a workshop cost?','The standard starting price is US$20. The price shown on your selected workshop is the amount that applies to your registration.'],['How do I pay?','Pay in person at '+office+'. Bring your registration reference. We issue a physical receipt and staff confirm your payment. There is no online checkout.'],['When is payment due?','Your workshop page and registration confirmation show the payment deadline. Please pay by that date, normally one week before training.'],['Is my seat confirmed when I register?','Registration starts as Payment Pending and reserves a place. Your seat is confirmed when staff record your in-person payment. Unpaid reservations may be cancelled by staff after the deadline.'],['Do I need an account?','No. Register with your contact details and save your reference number. Use the reference and the same phone number to check your status.'],['What if I need to cancel or change details?','Contact our office with your reference number. Our team can explain the options for your workshop.'],['Will I get a certificate?','Ask our team about certificate eligibility for your chosen workshop. Issued certificates can be checked on the verification page.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
{page==='contact'&&<div className="two-grid"><div><p className="eyebrow">VISIT OUR OFFICE</p><h2>Start a conversation.</h2><p className="lead">{office}</p><p>Contact us to arrange your visit and confirm office hours before travelling to pay.</p><div className="payment-note">Physical receipts issued for in-person payments.</div></div><div className="contact-card"><h3>Phone & WhatsApp</h3><a href="tel:+231770716497">0770716497</a><a href="tel:+231775972161">0775972161</a><div className="button-row"><a className="button" href="https://wa.me/231770716497">WhatsApp 1 ↗</a><a className="button secondary" href="https://wa.me/231775972161">WhatsApp 2 ↗</a></div><h3>Email</h3><a className="break" href="mailto:moderncommunicationlinks@gmail.com">moderncommunicationlinks@gmail.com</a><h3>Follow along</h3><a href="https://www.facebook.com/share/1GjjkcvZhK/?mibextid=wwXlfr" target="_blank" rel="noreferrer">Find us on Facebook ↗</a></div></div>}
</section></>}