import {WhatsAppLink} from './site-settings-provider';
import {ShareWorkshop} from './share-workshop';
import Link from 'next/link';
import {ArrowUpRight,CalendarDays,MapPin,Check,Clock3} from 'lucide-react';
import type {Content,Workshop} from '@/lib/schema';
import {dateLabel} from '@/lib/public-data';
export const topics=[{number:'01',title:'Get comfortable with AI',text:'Understand what AI can do, where it can go wrong, and how to use it responsibly.',tag:'FOUNDATIONS'},{number:'02',title:'Turn ideas into useful work',text:'Practice writing better prompts and using AI for everyday writing, planning, and research.',tag:'HANDS-ON PRACTICE'},{number:'03',title:'Make something of your own',text:'Bring your skills together in a practical project and leave with a way to keep learning.',tag:'YOUR NEXT STEP'}];
export function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="page-heading wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children&&<div className="lead">{children}</div>}</div>}
export function ProgramCards(){return <div className="three-grid">{topics.map(t=><article className="topic-card" key={t.number}><div className="topic-top"><span>{t.number}</span><ArrowUpRight size={23}/></div><p className="eyebrow">{t.tag}</p><h3>{t.title}</h3><p>{t.text}</p></article>)}</div>}
export function WorkshopList({workshops,state='ready'}:{workshops:Workshop[];state?:string}){const upcoming=workshops.filter(w=>new Date(w.endAt).getTime()>Date.now());return upcoming.length ? <div className="workshop-list">{upcoming.map(w=>{const open=Date.now()<=Date.parse(w.registrationDeadline)&&w.reserved<w.capacity;return <article className="workshop-card" key={w.id}><div><span className="pill">{open?'Registration open':'Registration closed'}</span><h3>{w.title}</h3><p>{w.summary}</p><div className="metadata"><span><CalendarDays size={17}/>{dateLabel(w.startAt)} – {dateLabel(w.endAt)}</span><span><MapPin size={17}/>{w.venue}, {w.city}</span><span><Clock3 size={17}/>{new Intl.DateTimeFormat('en-GB',{timeStyle:'short',timeZone:'Africa/Monrovia'}).format(new Date(w.startAt))} start · Liberia time</span></div><p className="fine">Register by {dateLabel(w.registrationDeadline)} · Pay by {dateLabel(w.paymentDeadline)}</p><details><summary>View workshop program & payment details</summary>{w.program.map((p,i)=><p key={i}><strong>{p.title}</strong><br/>{p.description}</p>)}<p>Pay in person at {w.paymentLocation}. Physical receipt issued.</p></details></div><div className="workshop-action"><span className="price">US${w.price}</span><p>per participant</p><span>{Math.max(0,w.capacity-w.reserved)} of {w.capacity} seats available</span>{open?<Link className="button" href={'/register?workshop='+w.id}>Register <ArrowUpRight size={18}/></Link>:<span className="pill">Closed</span>}<ShareWorkshop workshopId={w.id} title={w.title}/></div></article>})}</div>:<div className="empty-state"><CalendarDays size={32}/><h3>{state==='error'?'Workshop details are temporarily unavailable':'Your next chapter is coming.'}</h3><p>{state==='error'?'Please try again shortly, or contact our team.':'New workshop dates will appear here when registration opens. Connect with us to hear about the next session.'}</p><WhatsAppLink className="button">Ask about the next workshop <ArrowUpRight size={18}/></WhatsAppLink></div>}
export function Trainers({content}:{content:Content}){return <div className="two-grid">{content.trainers.map((t,i)=><article className="trainer" key={i}>{t.photoUrl?<img src={t.photoUrl} alt={t.name} loading="lazy" width={100} height={100}/>:<div className="avatar" aria-hidden="true">{t.name.split(' ').map(n=>n[0]).join('')}</div>}<div><h3>{t.name}</h3><p className="trainer-title">{t.title||'Trainer profile coming soon'}</p><p>{t.bio||'A full introduction will be added here soon.'}</p></div></article>)}</div>}
export function PaymentNote(){return <div className="payment-note"><Check size={21}/><div><strong>Register online. Pay in person.</strong><p>No online payment is needed. Bring your reference number to our office before your workshop’s payment deadline. We’ll issue a physical receipt and confirm your seat.</p></div></div>}