'use client';
import {useEffect,useState,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import type {User} from 'firebase/auth';
import type {SiteSettings} from '@/lib/site-settings';
export function SettingsEditor({user}:{user:User}){
 const router=useRouter();const [value,setValue]=useState<SiteSettings|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/settings',{headers:{Authorization:'Bearer '+await user.getIdToken()},cache:'no-store'});const result=await r.json();if(!r.ok)throw new Error(result.error);setValue(result);}catch(e){setError(e instanceof Error?e.message:'Unable to load settings.');}finally{setBusy(false);}},[user]);
 useEffect(()=>{void load();},[load]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await user.getIdToken()},body:JSON.stringify(value)});const result=await r.json();if(!r.ok)throw new Error(result.error);setNotice('Website settings saved.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save settings.');}finally{setBusy(false);}}
 return <section>{error&&<p role="alert" className="alert error">{error}</p>}{notice&&<p role="status" className="alert">{notice}</p>}{!value?<><p role="status">{busy?'Loading settings…':'Settings unavailable.'}</p><button className="button secondary" disabled={busy} onClick={load}>Reload settings</button></>:<form className="form-card" onSubmit={save}><h2>Website settings</h2><h3>Contact information</h3><div className="two-grid">{(['phone1','phone2','email','facebook'] as const).map(key=><label key={key}>{{phone1:'Primary phone / WhatsApp',phone2:'Second phone / WhatsApp',email:'Email',facebook:'Facebook link'}[key]}<input required type={key==='email'?'email':key==='facebook'?'url':'tel'} value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}</div><label>Office / default payment address<textarea required maxLength={400} value={value.office} onChange={e=>setValue({...value,office:e.target.value})}/></label><label>Default price for new workshops (USD)<input type="number" min={0} max={10000} step="0.01" required value={value.defaultPrice} onChange={e=>setValue({...value,defaultPrice:Number(e.target.value)})}/></label><p className="fine">Existing workshop prices, payment locations, and participant amounts stay unchanged. Edit each workshop separately when needed.</p><h3>Homepage</h3>{(['heroLine1','heroLine2','heroLine3'] as const).map((key,i)=><label key={key}>Headline line {i+1}<input required maxLength={100} value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}<label>Introduction<textarea required maxLength={600} value={value.heroDescription} onChange={e=>setValue({...value,heroDescription:e.target.value})}/></label><h3>About page</h3><label>About your organisation<textarea rows={8} required maxLength={4000} value={value.about} onChange={e=>setValue({...value,about:e.target.value})}/></label><button className="button" disabled={busy}>{busy?'Saving…':'Save website settings'}</button></form>}</section>;
}
